FROM node:gallium-bullseye

RUN npm i -g pnpm

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 3000

ENV VITE_BASE_URL=http://localhost:8000/api

CMD ["pnpm", "vite"]