FROM node:gallium-slim

RUN npm i -g pnpm

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

EXPOSE 3000

ENV REACT_APP_BASE_URL=http://localhost:8000/api

CMD ["pnpm", "start"]