# FROM node:16-slim
FROM node:fermium-alpine3.15

WORKDIR /usr/src/app

COPY ./package.json ./
COPY ./package-lock.json ./

RUN npm install

COPY . .

EXPOSE 3000

ENV REACT_APP_BASE_URL=http://localhost:8000/api

CMD ["npm", "run", "start"]