# First stage
FROM node:gallium-bullseye AS builder

RUN npm i -g pnpm

WORKDIR /usr/src/app

COPY package.json pnpm-lock.yaml ./

RUN pnpm install

COPY . .

ARG BASE_URL
ENV VITE_BASE_URL=${BASE_URL}

RUN pnpm build

# Second stage
# FROM caddy:2.1.1
FROM caddy:2.6.2-alpine

ARG CADDYFILE
COPY ${CADDYFILE} /etc/caddy/Caddyfile

COPY --from=builder /usr/src/app/build/ /srv

EXPOSE 80

EXPOSE 443