services:
  react-app:
    image: react-app-dev
    build:
      context: ./client/
      dockerfile: Dockerfile.dev
    stdin_open: true
    ports:
      - '3000:3000'
    networks:
      - mern-app
    volumes:
      - ./client/:/usr/src/app
      - /usr/src/app/node_modules
  api-server:
    image: api-server
    build:
      context: ./server/
      dockerfile: Dockerfile
    env_file: ./server/config/.env.dev
    ports:
      - '8000:8000'
    networks:
      - mern-app
    volumes:
      - ./server/:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo
  mongo:
    # I had to use this mongo image because my Mac OS runs on M1 chip, if you have a Linux or Intel compatible chip, you can use a normal mongo image
    image: arm64v8/mongo:8.0.4
    #To connect to mongo database using MongoDB Compass UI, use: mongodb://localhost:27020
    ports:
      - '27020:27017'
    networks:
      - mern-app
    volumes:
      - mongo-data:/data/db
networks:
  mern-app:
    driver: bridge
volumes:
  mongo-data:
    driver: local
